### ISSUE TITLE
Color Output lost with Indent

### ISSUE THREAD

**Issue by WaylonWalker** [kennethreitz/bake#3]
When Running an output with color involved such as `pytest` or `ls` the color codes get lost. Love the project, and will be using it whether there is a fix for this or not.  This is definitely not a show stopper for using such a great too.

# Attempted Resolution

I attempted to fork the project and tried several different intent options with no luck.  I even tried emoving the indent all together by implementing a `--no-indent` flag, but it still was not quite right.  If I run `bake ls --debug` copy the command and remove the ` | bake:indent` it works correctly. 

# My System
I am on a windows 10 system running debian wsl.

# Example
```
# Bakefile
ls:
    ls -laht --color=tty
```

![bakecolor](https://user-images.githubusercontent.com/22648375/65006697-7b4a3e00-d8c9-11e9-98fc-eedf4a6d55e3.gif)

**Comment by jpas** [comment]
This is probably due to `ls` detecting that it is being piped into another process, as opposed to a tty.

If you use `--color=always` instead it should as you would like it to.

In terms of adding functionality to bake to not force the user to use `--color=always`, bake would need to emulate a tty, an option would be to use [`pty.spawn`](https://docs.python.org/3/library/pty.html#pty.spawn) instead of `os.system`.

**Comment by kennethreitz** [comment]
I have a solution to this, actually. It involves using `unbuffer` from the `expect` project.

I've had it in there, but ripped it out. Torn.

**Comment by kennethreitz** [comment]
I added a `--interactive` / `-i` flag, which disables the piping.

**Comment by kennethreitz** [comment]
I'm also scrubbing your environment variables. Run `env` under `bake`, and on your native system — compare the difference. This is actually the primary cause of this particular instance :)

**Comment by WaylonWalker** [comment]
Took a quick peek at ls and looks much better, still not same though.  I'll check out pytest later today.  Thanks for your comments here and everything you do for the python community!
